name: Update Lock
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Update flake.lock
      run: nix flake update
    - name: Push commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update flake.lock
        branch: main
        file_pattern: flake.lock
